### ISSUE TITLE
Unable to build from base image that already has puppet

### ISSUE THREAD

**Issue by cyberious** [puppetlabs/puppetlabs-image_build#11]
When trying to run against a base container that has already been built using puppet docker build it fails with the following error message

```
INFO[0001] RUN rpm -Uvh https://yum.puppetlabs.com/puppetlabs-release-pc1-el-6.noarch.rpm &&     yum upgrade -y &&     yum update -y &&     yum install -y puppet-agent-"$PUPPET_AGENT_VERSION" &&     yum clean all 
INFO[0002] | Created container 2a95bf529cf7 (image sha256:35047) 
Retrieving https://yum.puppetlabs.com/puppetlabs-release-pc1-el-6.noarch.rpm
Preparing...                ##################################################
	package puppetlabs-release-pc1-1.1.0-4.el6.noarch (which is newer than puppetlabs-release-pc1-1.1.0-2.el6.noarch) is already installed
INFO[0005] | Removing container 2a95bf529cf7            
FATA[0005] Container 2a95bf529cf7 exited with code 2    
```

**Comment by cyberious** [comment]
This appears to be an issue with the rocker implementation and yum stating puppet-agent is still installed.

**Comment by garethr** [comment]
Mmm, thinking about this I see two options.

1. Modify some of the install commands to be idempotent
2. Make this an explicit part of the UI, ie. the ability to disable the installation of Puppet

I'm leaning towards 2 as I think in this case being explicit is desirable. Going the route of 1 still leaves layers floating around. What do you think?

**Comment by cyberious** [comment]
The problem is that with rocker you are mounting puppet and the files will be removed on subsequent runs as it is not part of the image. But yum seems to think it is installed still so would need to do reinstall.

**Comment by luckyraul** [comment]
+1 for second option.
If I need to build an image with small option, I prefer to extend the main image with additional options layers

**Comment by garethr** [comment]
#17 has some prior-art for an explicit skip install option. I'm currently extracting parts out into separate PRs and testing/adding documentation.

**Comment by garethr** [comment]
Apologies for taking a while to get back to issues on this. I've just added the ability to skip the puppet installation step in https://github.com/puppetlabs/puppetlabs-image_build/commit/8be09670fc17152c9bceca9d44d58a710736d98a.
