### ISSUE TITLE
passing facts in

### ISSUE THREAD

**Issue by walkamongus** [puppetlabs/puppetlabs-image_build#13]
Is there any current way to pass facts down into the `puppet apply` or `puppet agent` commands that run inside the containers?

I'd like to be able to point to my current master and set a list of facts in order to "mimic" a container build of a current node configuration.

**Comment by sheenaajay** [comment]
Sorry for the delay.

@walkamongus.Yes we have now an option to pass custom file.Please find the command

puppet docker build --factfile custom_facts.txt

This PR is merged recently.@jonaldee
https://github.com/puppetlabs/puppetlabs-image_build/pull/14

**Comment by sheenaajay** [comment]
Please let me know if you need more information
