### ISSUE TITLE
Git r10k

### ISSUE THREAD

**Issue by luckyraul** [puppetlabs/puppetlabs-image_build#21]
May be it not a good idea to remove git before r10k installs modules ? 

```
Step 6/12 : RUN /opt/puppetlabs/puppet/bin/r10k puppetfile install --moduledir /etc/puppetlabs/code/modules
 ---> Running in 146dca567f57
ERROR	 -> No Git providers are functional.
```

**Comment by luckyraul** [comment]
also ca-certificates

**Comment by garethr** [comment]
Thanks, agreed. I've opened #25 to resolve this and will merge and release a new version next week all being well.
