### ISSUE TITLE
Ability to used different facts defined at hiera.yaml 

### ISSUE THREAD

**Issue by mativillagra** [puppetlabs/puppetlabs-image_build#29]
Hello, 

I'm trying this puppet module with success! Building a Centos OS image using the nginx example including Hiera. I have a simple question, I hope you can guide me through.

Taking the elasticsearch example where you use hiera, (puppetlabs-image_build/examples/elasticsearch/) you specified the hierarchy tree starting with common, this works perfectly fine if I run 

puppet docker build --image-name puppet/nginx --from centos:6 --no-inventory

This take into account the use of the common.yaml you express the variables i.e. 

elasticsearch::version: 2.3.4
elasticsearch::manage_repo: true

My question is if you write your hierarchy at hiera.yaml file as

:hierarchy:
  - prod
  - dev
  - common

:backends:
  - yaml

:yaml:
  :datadir: '/hieradata'

Specifying different versions of elasticsearch to install as parameters values on prod/dev facts, How can I construct using the module, one image using prod other using dev?

My guess was to use something like, but this failed to build.

puppet docker build --image-name puppet/nginx --from centos:6 --no-inventory --hiera-config hieradata/prod.yaml 

Thanks in advance.

**Comment by garethr** [comment]
The hiera-config option is for changing the hiera config file itself, ie. the `hiera.yaml` file eg. https://github.com/puppetlabs/puppetlabs-image_build/blob/master/examples/elasticsearch/hiera.yaml

If you wanted completely separate configs for each environment you could use the `hiera-data` option to switch between different entire directories. But if you do want a common file and a single hiera directory you can use a FACT to toggle between them.

I think the following show work:

```
$ ls hieradata
common.yaml
prod.yaml
dev.yaml
```

The `image_type` name is arbitrary. We're using the fact `facter` will pick up ENV variables prefixed with `FACTER_` and convert it into a fact.

```
$ cat hiera.yaml
:hierarchy:
  - %{::image_type}
  - common
:backends:
  - yaml
:yaml:
  :datadir: '/hieradata'
```

We then pass that environment variable along to the builder.

```
$ puppet docker build --image-name puppet/nginx --from centos:6 --no-inventory --env FACTER_image_type=dev
```

Let me know if you try this out, and if it doesn't work I'll put together a proper example.
