### ISSUE TITLE
Entrypoint array missing commas

### ISSUE THREAD

**Issue by oc243** [puppetlabs/puppetlabs-image_build#32]
If you use the `--entrypoint` option with an array (eg `--entrypoint '["nginx", "-g", "daemon off"]'`) then the resulting Dockerfile removes the commas from the array: ` Step 9 : ENTRYPOINT ["nginx"  "-g"  "daemon off"]`. This is invalid syntax and the resulting Dockerfile fails to run.

The Dockerfile should be produced with `ENTRYPOINT ["nginx", "-g", "daemon off"]`.

**Comment by garethr** [comment]
Ah, the invocation here is incorrect, but not caught with the validation. The correct way of achieving what you want is to pass values as comma separated, like so:

```
--entrypoint nginx,'-g','daemon off'
```

This correctly renders:

```
ENTRYPOINT ["nginx", "-g", "daemon off"]
```

I'll leave this open until I can add better documentation.

**Comment by garethr** [comment]
I've updated the docs with a note about this for others that run across it. Thanks for flagging https://github.com/puppetlabs/puppetlabs-image_build/commit/8ce116560d99978b1c2a7dd45cbfa4e7a6e587e5
