### ISSUE TITLE
set show diff optional

### ISSUE THREAD

**Issue by luckyraul** [puppetlabs/puppetlabs-image_build#34]
In some cases --show_diff create an error ```Error: invalid byte sequence in US-ASCII``` trying to compare file even if you are replacing it completely.

Since inside most docker images has not set correct locale -  it fails build

**Comment by garethr** [comment]
Mmm, I've provided a flag to disable this for now, `--[no-]show-diff`. Added in https://github.com/puppetlabs/puppetlabs-image_build/commit/a16383298e7663d22208b99dc9f6548242533cfc

If I get more reports about this I'll flip the default behaviour but this is currently enabled by default. Thanks (and apologies for taking a while to get to some of these issues.)
