### ISSUE TITLE
Will not work with Centos

### ISSUE THREAD

**Issue by aaron-grewell** [puppetlabs/puppetlabs-image_build#36]
In imagebuilder.rb, def determine_environment_vars currently has no section for centos but returns an error stating centos is supported.

**Comment by garethr** [comment]
@aaron-grewell apologies, I'll get that fixes. I've been slightly over zealous in fixing a style issue in https://github.com/puppetlabs/puppetlabs-image_build/commit/c4e6991126ca0ee9aab5faf178a9a9d23c175992#diff-5b6bb399d2fbcb9e0c09e42aa7ac6512

**Comment by garethr** [comment]
I've a PR up for this in https://github.com/puppetlabs/puppetlabs-image_build/pull/37. We'll get that merged and a new release pushed to the Forge.

**Comment by aaron-grewell** [comment]
Thanks Gareth!  That definitely seemed to do the trick.  I was going to suggest that test coverage include centos but it looks like it should.  At least the acceptance tests include a centos node (apologies, my spec-fu is weak).  It's surprising to me that it wasn't picked up by the tests.

**Comment by garethr** [comment]
I've added unit tests to that PR that will trigger the issue in Travis too, which should prevent this in the future. Thanks for checking out the issue.

**Comment by garethr** [comment]
Fixed in #37
