### ISSUE TITLE
Build not failing on apply failures

### ISSUE THREAD

**Issue by luckyraul** [puppetlabs/puppetlabs-image_build#38]
Changes:
            Total: 19
Events:
          Success: 19
          Failure: 2
            Total: 21

**Comment by luckyraul** [comment]
```
The command '/bin/sh -c apt-get update &&     FACTER_hostname=php:7.0-full /opt/puppetlabs/bin/puppet apply manifests/init.pp --detailed-exitcodes --verbose  --summarize --hiera_config=/hiera.yaml --app_management ;     rc=$?; if [ $rc -ne 0 ] && [ $rc -ne 2 ]; then exit 1; fi &&     apt-get autoremove -y &&     apt-get clean &&     rm -rf /var/lib/apt/lists/*' returned a non-zero code: 1
```

however https://github.com/Shippable/support/issues/3477

**Comment by garethr** [comment]
Hi @luckyraul. Could you provide a bit more information regarding this issue? Ideally a manifest and the invocation of the CLI  you used to trigger it, along with the output and your expectations?

**Comment by luckyraul** [comment]
@garethr 

i've just created sample, it is very easy to repeat.

manifest
```
package {'php8':
    ensure: installed
}
```

puppet docker build --image-name luckyraul/sample

exited with code 0

**Comment by luckyraul** [comment]
@garethr Any update related to this issue?

**Comment by garethr** [comment]
@luckyraul apologies, I've been working on other things recently. The last few days I've been catching up and making a few improvements. I've just fixed this issue in https://github.com/puppetlabs/puppetlabs-image_build/commit/d222ed356140dc401d22be7dd9482c107b2e3a77 along with an acceptance test which demonstrates the fix. Thanks for reporting. This should be in a new release today or tomorrow as well.
