### ISSUE TITLE
Build w/ Docker master on Mac isn't actually.. easy.

### ISSUE THREAD

**Issue by matthewbarr** [puppetlabs/puppetlabs-image_build#39]
I was trying out some of the examples, and while most work great on a Docker for Mac environment, building using a master, especially the new local master wasn't as easy.

I ended up having to install puppet-agent for the Mac (not shocking), but then also figuring out how to get r10K onto the mac, since it's not included in the agent packaging.   (I'd been tempted to try to use the ubuntu-docker container, or the actual puppet-server container, but this was probably better.  Maybe this should be in the standard agent?)

`sudo /opt/puppetlabs/puppet/bin/gem install r10k`
`sudo ln -s /opt/puppetlabs/puppet/bin/r10k  /opt/puppetlabs/bin/r10k`

The largest issue I had was actually determining the IP to use for the puppet master.  Docker build can't use a docker network, oddly enough, and you don't want to use the port exposed to the mac for the puppet server.

You may want to do something like this as your puppet image build command:
```
puppet docker build  --master `docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' puppet` --image-name puppet/node1 --expose 80 --cmd nginx
```

That will determine the IP of the container from the prior line, and use that to populate the docker build command.  It turns out you can specify network for dockerfile  commands.   Which would mean adding the --network option to likely both  metadata  and the command line.

I'd make this a pull request, but I'm not sure how you'd like this formatted for intelligibility.  I suspect the tech writer types have opinions on this, and my slapdash method probably isn't it...

**Comment by matthewbarr** [comment]
I can fairly easily see the template for the docker file, will go looking for the code to accept the command line option --network and the area that deals with metadata files.

**Comment by matthewbarr** [comment]
(Ugh.  Forgot how little I want to look at types & provider type code. I'm too far out of the the habit to do this on a sunday night :)

**Comment by garethr** [comment]
@matthewbarr thanks for the suggestion of adding network passthrough support to make this a bit easier. I've added this in https://github.com/puppetlabs/puppetlabs-image_build/commit/2071e7a9e110bf720b71a3e26bdd82b899e535dd and it will be in the release shortly.
