### ISSUE TITLE
Pass `--debug` to puppet apply

### ISSUE THREAD

**Issue by oc243** [puppetlabs/puppetlabs-image_build#42]
It would be nice to be able to apply `--debug` to `puppet apply` to get more log info when debugging. It looks like this module can't currently do that (the `-debug` to `puppet docker build` debugs this module, not the puppet). I don't mind writing the patch for adding this functionality. Would you rather introduce a new flag (maybe `--debug-puppet`) or make the existing `-debug` also debug the puppet?

**Comment by garethr** [comment]
@oc243 good idea, and apologies I missed this when you first posted it. I've just added this now https://github.com/puppetlabs/puppetlabs-image_build/commit/a38fed181ddafe58c9b178eb30cfc7106ab2fa87 and it's available from 0.5.0. Thanks again.
