### ISSUE TITLE
Add Support for base images build on supported base images

### ISSUE THREAD

**Issue by bseb** [puppetlabs/puppetlabs-image_build#46]
Need support for using images created on a supported OS base as a base for a new image.  Many public Docker images are built on Ubuntu, CentOS, etc and it would be more efficient to extend upon them than recreate the wheel.

**Comment by garethr** [comment]
@bseb The `--from` option allows for what I think you're referring to? You should be able to use that at the command line or in the metadata file to build upon an existing base image. Let me know if that doesn't work, or I've missed the problem you're having. Thanks.

**Comment by barrymw** [comment]
If the `puppet docker --from custom_base build` fails, try adding the `--os os_family` parameter:
```console
# puppet docker --from ccc_centos:7 build               
Error: puppet docker currently only supports Ubuntu, Debian, Alpine and Centos base images
Error: Try 'puppet help docker build' for usage
```
With `--os`
```console
# puppet docker --from ccc_centos:7 --os centos --skip-puppet-install build
Sending build context to Docker daemon  6.144kB
Step 1/11 : FROM ccc_centos:7
 ---> 6946d004e07c
```
Now to reverse engineer the code to work out where/how to get build args through to the docker build.
