### ISSUE TITLE
Docker multistage build

### ISSUE THREAD

**Issue by luckyraul** [puppetlabs/puppetlabs-image_build#48]
Hi @garethr , Just want to notice you about new functionality in docker platform. 
https://docs.docker.com/engine/userguide/eng-image/multistage-build/

We can make new images without puppet agent in them

**Comment by garethr** [comment]
@luckyraul thanks for posting, I've been using multi-stage builds for a bunch of things recently. Unfortunately they don't help here apart from in very specific cases. Multi-stage builds rely on copying things across from one container to the next. In the case of using image_build you won't know what to copy across (for instance if you installed a package). If you have a specific idea of how this might be used please do let me know however, I'm still pondering it.
