### ISSUE TITLE
Building from master - not doing anything?

### ISSUE THREAD

**Issue by KlavsKlavsen** [puppetlabs/puppetlabs-image_build#49]
I setup my master to autosign *.dockerbuilder - and gave *.dockerbuild a node definition, that includes a role-  that only installs a few packages.

When trying to run it:
 puppet docker dockerfile --master puppet.internal.org:8140 --image-name puppet/oase_ci_image --cmd bash

I get this the output below - but no image is built?:
```
FROM ubuntu:16.04

ENV PUPPET_AGENT_VERSION="1.8.2" R10K_VERSION="2.2.2" CODENAME="xenial" 

RUN apt-get update && \
    apt-get install --no-install-recommends -y lsb-release wget ca-certificates && \
    wget https://apt.puppetlabs.com/puppetlabs-release-pc1-"$CODENAME".deb && \
    dpkg -i puppetlabs-release-pc1-"$CODENAME".deb && \
    rm puppetlabs-release-pc1-"$CODENAME".deb && \
    apt-get update && \
    apt-get install --no-install-recommends -y puppet-agent="$PUPPET_AGENT_VERSION"-1"$CODENAME" && \
    apt-get remove --purge -y wget && \
    apt-get autoremove -y && \
    apt-get clean && \
    mkdir -p /etc/puppetlabs/facter/facts.d/ && \
    rm -rf /var/lib/apt/lists/* 

  
    
RUN apt-get update && \
    FACTER_hostname=oase_ci_image.20170724T1432200200.dockerbuilder /opt/puppetlabs/bin/puppet agent --server puppet.yousee.idk --masterport 8140 --verbose --onetime --no-daemonize --show_diff --summarize && \
    apt-get autoremove -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* 
    
  

LABEL com.puppet.inventory="/inventory.json"
RUN /opt/puppetlabs/bin/puppet module install puppetlabs-inventory && \
    /opt/puppetlabs/bin/puppet inventory all > /inventory.json

CMD ["bash"]
```

**Comment by KlavsKlavsen** [comment]
I see no logs in puppetserver about it even trying to connect to my puppetserver instance.

**Comment by KlavsKlavsen** [comment]
If I try with puppet docker build (and same options as above) - I get this error:
Error: No such file or directory - fork failed
Error: Try 'puppet help docker build' for usage

**Comment by garethr** [comment]
Hi @KlavsKlavsen. If you could try this in a few steps I'll try and help debug.

First save the Dockerfile to disk.

```
puppet docker dockerfile <your-args-here> > Dockerfile
```

And then try and use Docker to build using that Dockerfile:

```
docker build -t <your-name-here> .
```

If you could print any output from those commands that would be helpful.

**Comment by KlavsKlavsen** [comment]
wow.. I'm appearently an idiot.. I was 100% certain I had installed docker.. but appearently NOT docker.io (which is the package name for docker in ubuntu).. sorry :(

**Comment by garethr** [comment]
@KlavsKlavsen thanks, glad that worked. I'l definitely look to improve that error message as that's not useful.
