### ISSUE TITLE
Will not work with centos:6

### ISSUE THREAD

**Issue by cyberious** [puppetlabs/puppetlabs-image_build#8]
When attempting to use with centos6 it doesn't respect the os_version when laying down the RPM to install the puppet agent, instead it is hard coded to 7.

```
tc_container [ ]$puppet docker build --os centos --os-version 6 --from centos:6
Sending build context to Docker daemon  7.68 kB
Step 1 : FROM centos:6
 ---> cf2c3ece5e41
Step 2 : ENV PUPPET_AGENT_VERSION "1.6.1" R10K_VERSION "2.2.2"
 ---> Using cache
 ---> dbcd696d5513
Step 3 : RUN rpm -Uvh https://yum.puppetlabs.com/puppetlabs-release-pc1-el-7.noarch.rpm &&     y
```

**Comment by garethr** [comment]
@cyberious cheers for the report, I've just fixed this up in master. This uncovered an additional issue, which is that inventory does not correctly run on Centos 6 at the moment. I've added this to the known issues list and will get it fixed, but the following should now work for you:

    puppet docker build --from centos:6 --no-inventory

Note that the tool should automatically detect centos as the os and 6 as the version from passing that specific from value. Any other problems let me know.

**Comment by walkamongus** [comment]
I can't seem to get centos 6 to work no matter what args I'm passing in. I'm always getting the following error:

```
$ puppet docker build --from centos:6 --no-inventory
Error: puppet docker currently only supports Ubuntu, Debian, Alpine and Centos base images
Error: Try 'puppet help docker build' for usage
```

if I switch to `--from alpine` it carries on normally and the default ubuntu from value seems to work.

**Comment by ccampanale** [comment]
I'm also seeing the above behavior. I cannot get any centos build or dockerfiles but other types at least try to build or create dockerfiles.

Running v0.1.2 which appears to point to the head of the master branch:

```
-bash-4.2$ puppet module list
/opt/go/go-agent3/.puppet/moules
└── puppetlabs-image_build (v0.1.2)
```

**Comment by ccampanale** [comment]
Upon further investigate, it appears to be an issue with this block of code: https://github.com/puppetlabs/puppetlabs-image_build/blob/master/lib/puppet_x/puppetlabs/imagebuilder.rb#L194L232

Since there is no case for 'centos' the block defaults to raising the InvalidContextError and fails. I've tested throwing a case in for centos here and setting the `puppet_version` and `facter_version` which seems to get things moving along.

**Comment by garethr** [comment]
Apologies, looks like I broke this in https://github.com/puppetlabs/puppetlabs-image_build/commit/c4e6991126ca0ee9aab5faf178a9a9d23c175992

For the moment I would recommend trying 0.1.1 where I think this should work. I'm on holiday this week but will fix and push a release next week. Thanks for the details @ccampanale and @walkamongus. I'll also be working on more comprehensive acceptance tests too soon.
